name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/java-8/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/java-8/
      - run: make 
      - name: Run a multi-line script
        run: |
          export PERCY_TOKEN=85cf7af9c352eac74225f75d00280d709f4890aa6651586e55b710bb5e3fe6e4
          make test
        
       
